// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM0dwNxZQn49sGk4ss4Y4hPaZjrAJYcec',
    appId: '1:309813168460:web:e807aa0c55af2d687827e9',
    messagingSenderId: '309813168460',
    projectId: 'sayna-18d2e',
    authDomain: 'sayna-18d2e.firebaseapp.com',
    storageBucket: 'sayna-18d2e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcKzXx2LT0N2InL7P-p4jb57EIpymwZWw',
    appId: '1:309813168460:android:dfd5780633ea95397827e9',
    messagingSenderId: '309813168460',
    projectId: 'sayna-18d2e',
    storageBucket: 'sayna-18d2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTKDPfiuGMR1I7os0fSfLZR4RVDz84nPc',
    appId: '1:309813168460:ios:702d3c6e53825f267827e9',
    messagingSenderId: '309813168460',
    projectId: 'sayna-18d2e',
    storageBucket: 'sayna-18d2e.appspot.com',
    iosBundleId: 'com.example.saynaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTKDPfiuGMR1I7os0fSfLZR4RVDz84nPc',
    appId: '1:309813168460:ios:702d3c6e53825f267827e9',
    messagingSenderId: '309813168460',
    projectId: 'sayna-18d2e',
    storageBucket: 'sayna-18d2e.appspot.com',
    iosBundleId: 'com.example.saynaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM0dwNxZQn49sGk4ss4Y4hPaZjrAJYcec',
    appId: '1:309813168460:web:a1c7d26440b82fb17827e9',
    messagingSenderId: '309813168460',
    projectId: 'sayna-18d2e',
    authDomain: 'sayna-18d2e.firebaseapp.com',
    storageBucket: 'sayna-18d2e.appspot.com',
  );
}
